services:
  server:
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: server
      env_file:
        - .env
      ports:
        - 3001:3000
      depends_on:
        - db
      command: |
        npm run start:migrate:prod

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - 5433:5432
    command: postgres