services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    command: |
      npm run start:migrate:prod
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 4000:4000
    depends_on:
      - server

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - 5433:5432
    command: postgres