services:
  postgresql:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    command: postgres
    restart: always